//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTables.MVC.Control.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTables.MVC.Control.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var initAjaxDataTable = function (tableId, colConfig, cbf) {
        ///    var languageFile = $(&apos;#&apos; + tableId).data(&quot;languagefile&quot;);
        ///    var ajaxUrl = $(&apos;#&apos; + tableId).data(&quot;ajaxurl&quot;);
        ///    var ajaxType = &quot;GET&quot;;
        ///    if ($(&apos;#&apos; + tableId).data(&quot;server-side&quot;) === true)
        ///        ajaxType = &quot;POST&quot;;
        ///    var dt = $(&apos;#&apos; + tableId).DataTable({
        ///        ajax: { &quot;url&quot;: ajaxUrl, &quot;type&quot;: ajaxType },
        ///        language: { &quot;url&quot;: languageFile },
        ///        columnDefs: colConfig
        ///    });
        ///    if (cbf !== undefined) {
        ///        dt.on [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string AjaxDataTableInitFunction {
            get {
                return ResourceManager.GetString("AjaxDataTableInitFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;use strict&quot;;var initAjaxDataTable=function(n,t,i){var f=$(&quot;#&quot;+n).data(&quot;languagefile&quot;),e=$(&quot;#&quot;+n).data(&quot;ajaxurl&quot;),r=&quot;GET&quot;,u;if($(&quot;#&quot;+n).data(&quot;server-side&quot;)===!0&amp;&amp;(r=&quot;POST&quot;),u=$(&quot;#&quot;+n).DataTable({ajax:{url:e,type:r},language:{url:f},columnDefs:t}),i!==undefined)u.on(&quot;draw&quot;,i)}; ähnelt.
        /// </summary>
        public static string AjaxDataTableInitFunction_es5_min {
            get {
                return ResourceManager.GetString("AjaxDataTableInitFunction_es5_min", resourceCulture);
            }
        }
    }
}
