//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxDopDowns.MVC.Control.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AjaxDopDowns.MVC.Control.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () { initAjaxDropDownList(&apos;{id}&apos;); }); ähnelt.
        /// </summary>
        internal static string AjaxDropDownListInitCall {
            get {
                return ResourceManager.GetString("AjaxDropDownListInitCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var initAjaxDropDownList = function (listId) {
        ///    var url = $(&apos;#&apos; + listId).data(&apos;url&apos;);
        ///    var value = $(&apos;#&apos; + listId).data(&apos;value&apos;);
        ///    var optionValue = $(&apos;#&apos; + listId).data(&apos;option-value&apos;);
        ///    var optionText = $(&apos;#&apos; + listId).data(&apos;option-text&apos;);
        ///    $.ajax({
        ///        cache: false,
        ///        url: url,
        ///        dataType: &quot;json&quot;,
        ///        success: function (data) {
        ///            var items = [];
        ///            var optionStart = &quot;&lt;option value=&apos;&quot;;
        ///            var optionEnd = &quot;&lt;/option&gt;&quot;;
        ///             [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AjaxDropDownListInitFunction {
            get {
                return ResourceManager.GetString("AjaxDropDownListInitFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;use strict&quot;;var initAjaxDropDownList=function(n){var i=$(&quot;#&quot;+n).data(&quot;url&quot;),r=$(&quot;#&quot;+n).data(&quot;value&quot;),u=$(&quot;#&quot;+n).data(&quot;option-value&quot;),t=$(&quot;#&quot;+n).data(&quot;option-text&quot;);$.ajax({cache:!1,url:i,dataType:&quot;json&quot;,success:function(i){var f=[],e=&quot;&lt;option value=&apos;&quot;,o=&quot;&lt;\/option&gt;&quot;;typeof t!=typeof undefined&amp;&amp;t!==!1&amp;&amp;f.push(e+u+&quot;&apos;&gt; &quot;+t+o);$.each(i,function(n,t){t.Value==r?f.push(e+t.Value+&quot;&apos; selected=&apos;selected&apos;&gt; &quot;+t.Text+o):f.push(e+t.Value+&quot;&apos;&gt;&quot;+t.Text+o)});$(&quot;#&quot;+n).html(f.join(&quot;&quot;))}})}; ähnelt.
        /// </summary>
        internal static string AjaxDropDownListInitFunction_es5_min {
            get {
                return ResourceManager.GetString("AjaxDropDownListInitFunction_es5_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die $(function () { initScriptDropDownList(&apos;{id}&apos;, &apos;{dataname}&apos;); }); ähnelt.
        /// </summary>
        internal static string ScriptDropDownListInitCall {
            get {
                return ResourceManager.GetString("ScriptDropDownListInitCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die var initScriptDropDownList = function (listId, data) {
        ///    var value = $(&apos;#&apos; + listId).data(&apos;value&apos;);
        ///    var optionValue = $(&apos;#&apos; + listId).data(&apos;option-value&apos;);
        ///    var optionText = $(&apos;#&apos; + listId).data(&apos;option-text&apos;);
        ///    var items = [];
        ///    var optionStart = &quot;&lt;option value=&apos;&quot;;
        ///    var optionEnd = &quot;&lt;/option&gt;&quot;;
        ///    if (typeof optionText !== typeof undefined &amp;&amp; optionText !== false) {
        ///        items.push(&quot;&lt;option value=&apos;&quot; + optionValue + &quot;&apos;&gt; &quot; + optionText + optionEnd);
        ///    };
        ///    $.each(data, func [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ScriptDropDownListInitFunction {
            get {
                return ResourceManager.GetString("ScriptDropDownListInitFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;use strict&quot;;var initScriptDropDownList=function(n,t){var e=$(&quot;#&quot;+n).data(&quot;value&quot;),o=$(&quot;#&quot;+n).data(&quot;option-value&quot;),r=$(&quot;#&quot;+n).data(&quot;option-text&quot;),i=[],f=&quot;&lt;option value=&apos;&quot;,u=&quot;&lt;\/option&gt;&quot;;typeof r!=typeof undefined&amp;&amp;r!==!1&amp;&amp;i.push(&quot;&lt;option value=&apos;&quot;+o+&quot;&apos;&gt; &quot;+r+u);$.each(t,function(n,t){t[0]==e?i.push(f+t[0]+&quot;&apos; selected=&apos;selected&apos;&gt; &quot;+t[1]+u):i.push(f+t[0]+&quot;&apos;&gt;&quot;+t[1]+u)});$(&quot;#&quot;+n).html(i.join(&quot;&quot;))}; ähnelt.
        /// </summary>
        internal static string ScriptDropDownListInitFunction_es5_min {
            get {
                return ResourceManager.GetString("ScriptDropDownListInitFunction_es5_min", resourceCulture);
            }
        }
    }
}
